services:
  - type: web
    name: myportfolio-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    port: 80
    envVars:
      - key: DB_HOST
        fromService:
          name: myportfolio-db
          type: pserv
          property: host
      - key: DB_NAME
        value: my-portfolio
      - key: DB_USER
        fromService:
          name: myportfolio-db
          type: pserv
          envVarKey: MYSQL_USER
      - key: DB_PASS
        fromService:
          name: myportfolio-db
          type: pserv
          envVarKey: MYSQL_PASSWORD
      - key: ALLOWED_ORIGINS
        value: "https://myportfolio-amie.onrender.com,https://myportfolio-livid-three-94.vercel.app,http://localhost:4200,http://localhost:8000"

  - type: pserv
    name: myportfolio-db
    runtime: docker
    dockerfilePath: ./Dockerfile.mysql
    dockerContext: ./
    plan: standard
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_DATABASE
        value: my-portfolio
      - key: MYSQL_USER
        value: portfolio_user
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
